language: python
python:
  - "3.6.4"
cache: pip3
install:
  - pip3 install -r requirements.txt
before_install:
  - pip3 install pytest pytest-cov
  - pip3 install coveralls
script:
  - pytest test_my_app.py
after_success:
  - coveralls