language: python
python:
  - "3.6.4"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install pytest pytest-cov
  - pip3 install coveralls
script:
  - python setup.py install
  - pytest test
  - pytest ttd
  - coverage run --source=test setup.py test
after_success:
  - coveralls